[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.fileinfo", "php82Extensions.gd", "apacheHttpd"]

[phases.build]
cmds = []

[start]
cmd = "apache2ctl -D FOREGROUND"

[variables]
PORT = "80"
